Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,19 +17,19 @@ jobs:
     # - name: Install dependencies
     #   run: npm install
 
-    # - name: Verify commit message format
-    #   run: |
-    #     if [[ $(git log -1 --pretty=%B) =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-    #       echo "Commit message format is correct."
-    #       echo $(git log -1 --pretty=%B)
-    #     else
-    #       echo "Error: Commit message format is incorrect. Please use the format 'vX.Y.Z'."
-    #       exit 1
-    #     fi
+    - name: Verify commit message format
+      run: |
+        if [[ $(git log -1 --pretty=%B) =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Commit message format is correct."
+          echo $(git log -1 --pretty=%B)
+        else
+          echo "Error: Commit message format is incorrect. Please use the format 'vX.Y.Z'."
+          exit 1
+        fi
 
     - name: Get version from tag
       id: get_version
-      run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
+      run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0) " >> "$GITHUB_OUTPUT"
       
 
       
