1.1.2

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,30 +9,33 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    # - name: Setup Node.js
-    #   uses: actions/setup-node@v2
-    #   with:
-    #     node-version: '20'
+    - name: Setup Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '20'
 
-    # - name: Install dependencies
-    #   run: npm install
+    - name: Install dependencies
+      run: npm install
 
-    # - name: Verify commit message format
-    #   run: |
-    #     if [[ $(git log -1 --pretty=%B) =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-    #       echo "Commit message format is correct."
-    #       echo $(git log -1 --pretty=%B)
-    #     else
-    #       echo "Error: Commit message format is incorrect. Please use the format 'vX.Y.Z'."
-    #       exit 1
-    #     fi
+    - name: Verify commit message format
+      run: |
+        if [[ $(git log -1 --pretty=%B) =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Commit message format is correct."
+          echo $(git log -1 --pretty=%B)
+        else
+          echo "Error: Commit message format is incorrect. Please use the format 'vX.Y.Z'."
+          exit 1
+        fi
 
-    - name: Get version from tag
+    - name: Get version from commit
       id: get_version
       run: echo "RELEASE_VERSION=$(git log -1 --pretty=%B)" >> "$GITHUB_OUTPUT"
-      # run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0) " >> "$GITHUB_OUTPUT"
       
-
+    - name: Create tag if not exists
+      run: git tag ${{ steps.get_version.outputs.RELEASE_VERSION }}
+    - name: Export tag variable
+      id: get_tag
+      run: echo "TAG=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
       
     - name: Check version
       run: echo "${{ steps.get_version.outputs.RELEASE_VERSION }}"
@@ -42,6 +45,6 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
-        tag_name: ${{ steps.get_version.outputs.RELEASE_VERSION }}
+        tag_name: ${{ steps.get_tag.outputs.TAG }}
         release_name: Release ${{ steps.get_version.outputs.RELEASE_VERSION }}
       
