Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,45 +2,45 @@ name: Release
 
 on: push
 jobs:
-  Create_release:
-    permissions: write-all
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+  # Create_release:
+  #   permissions: write-all
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@v2
         
-    - name: Verify commit message format
-      run: |
-        if [[ $(git log -1 --pretty=%B) =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          echo "Commit message format is correct."
-          echo $(git log -1 --pretty=%B)
-        else
-          echo "Error: Commit message format is incorrect. Please use the format 'vX.Y.Z'."
-          exit 1
-        fi
-    - name: Get version from commit
-      id: get_version
-      run: echo "RELEASE_VERSION=$(git log -1 --pretty=%B)" >> "$GITHUB_OUTPUT"
+  #   - name: Verify commit message format
+  #     run: |
+  #       if [[ $(git log -1 --pretty=%B) =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+  #         echo "Commit message format is correct."
+  #         echo $(git log -1 --pretty=%B)
+  #       else
+  #         echo "Error: Commit message format is incorrect. Please use the format 'vX.Y.Z'."
+  #         exit 1
+  #       fi
+  #   - name: Get version from commit
+  #     id: get_version
+  #     run: echo "RELEASE_VERSION=$(git log -1 --pretty=%B)" >> "$GITHUB_OUTPUT"
       
-    - name: Create tag if not exists
-      run: git tag ${{ steps.get_version.outputs.RELEASE_VERSION }}
-    - name: Export tag variable
-      id: get_tag
-      run: echo "TAG=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
+  #   - name: Create tag if not exists
+  #     run: git tag ${{ steps.get_version.outputs.RELEASE_VERSION }}
+  #   - name: Export tag variable
+  #     id: get_tag
+  #     run: echo "TAG=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"
       
-    - name: Check version
-      run: echo "${{ steps.get_version.outputs.RELEASE_VERSION }}"
+  #   - name: Check version
+  #     run: echo "${{ steps.get_version.outputs.RELEASE_VERSION }}"
       
-    - name: Create GitHub Release
-      id: create_release
-      uses: actions/create-release@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        tag_name: ${{ steps.get_tag.outputs.TAG }}
-        release_name: Release ${{ steps.get_version.outputs.RELEASE_VERSION }}
-    - name: Export url release
-      run: echo "RELEASE_URL=${{steps.create_release.outputs.upload_url}}" >> "$GITHUB_ENV"
+  #   - name: Create GitHub Release
+  #     id: create_release
+  #     uses: actions/create-release@v1
+  #     env:
+  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     with:
+  #       tag_name: ${{ steps.get_tag.outputs.TAG }}
+  #       release_name: Release ${{ steps.get_version.outputs.RELEASE_VERSION }}
+  #   - name: Export url release
+  #     run: echo "RELEASE_URL=${{steps.create_release.outputs.upload_url}}" >> "$GITHUB_ENV"
 
   Create-windows-build:
     runs-on: windows-latest
@@ -61,13 +61,13 @@ jobs:
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Upload build to release
-      id: upload-release-asset 
-      uses: actions/upload-release-asset@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: $RELEASE_URL
-        asset_path: ./release/${{ steps.get_tag.outputs.TAG }}/*.exe
-        asset_name: Inventario-Windows-${{steps.get_tag.outputs.TAG }}-Setup.exe
-        asset_content_type: application/octet-stream
+    # - name: Upload build to release
+    #   id: upload-release-asset 
+    #   uses: actions/upload-release-asset@v1
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #   with:
+    #     upload_url: $RELEASE_URL
+    #     asset_path: ./release/${{ steps.get_tag.outputs.TAG }}/*.exe
+    #     asset_name: Inventario-Windows-${{steps.get_tag.outputs.TAG }}-Setup.exe
+    #     asset_content_type: application/octet-stream
