Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,39 +1,41 @@
-name: Build/release
+name: Release
 
-on: push
-
+on:
+  push:
+    paths:
+      - 'package.json'
 jobs:
   release:
-    permissions: write-all
-    runs-on: windows-latest
+    runs-on: ubuntu-latest
     steps:
-        
-      - name: Create Release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          release_name: ${{ steps.release_info.outputs.version }}
-          tag_name: 1.1.2
-      - name: Check out Git repository
-        uses: actions/checkout@v1
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-      - name: Install Node.js, NPM and Yarn
-        uses: actions/setup-node@v1
-        with:
-          node-version: 16
-      - name: Install dependencies
-        run: npm install
-        
-      - name: Build/release Electron app
-        uses: paneron/action-electron-builder@v1.8.1
-        with:
-          # GitHub token, automatically provided to the action
-          # (No need to define this secret in the repo settings)
-          package_manager: npm
-          github_token: ${{ secrets.github_token }}
-          build_script_name: build
-          # If the commit is tagged with a version (e.g. "v1.0.0"),
-          # release the app after building
-          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
-          
+    - name: Setup Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '20'
+
+    - name: Install dependencies
+      run: npm install
+
+    - name: Verify commit message format
+      run: |
+        if [[ $(git log -1 --pretty=%B) =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Commit message format is correct."
+        else
+          echo "Error: Commit message format is incorrect. Please use the format 'vX.Y.Z'."
+          exit 1
+        fi
+
+    - name: Get version from commit
+      id: get_version
+      run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
+
+    - name: Create GitHub Release
+      uses: actions/create-release@v1
+      with:
+        tag_name: ${{ steps.get_version.outputs.version }}
+        files: dist/*
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
